# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.2
apiVersion: v1
kind: Service
metadata:
  labels:
    app: code-server1-pod
  name: code-server1-pod
  namespace: code-server
spec:
  ports:
    - name: "8443"
      nodePort: 31732
      port: 8443
      targetPort: 8443
  selector:
    app: code-server1-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: code-server1-pod
  name: code-server1-pod
spec:
  securityContext:
    runAsUser: 0
    privileged: true
  containers:
    - env:
        - name: PASSWORD
          value: for_service_portal
        - name: DEFAULT_WORKSPACE
          value: /config/workspace
        - name: TZ
          value: Asia/Tokyo
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
      image: quay.io/jiadchen/code-server-php8
      name: code-server1
      ports:
        - containerPort: 8443
          hostPort: 8443
