---
version: "2.1"
services:
  code-server:
    image: localhost/code-server-nodejs16:latest
    container_name: code-server1
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Tokyo
      - PASSWORD=password #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
    #   - /Users/jiadong.chen/git/container/code-server/server1/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped