---
version: "2.1"
services:
  code-server1:
    image: localhost/code-server-nodejs16:latest
    container_name: code-server1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${PASSWORD} #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
    #   - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
  code-server2:
    image: localhost/code-server-nodejs16:latest
    container_name: code-server2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=dfIhfkJdHHSDes #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
    #   - ./config:/config
    ports:
      - 8444:8443
    restart: unless-stopped
