---
version: "2.1"
services:
  code-server1:
    image: localhost/code-server-php8:latest
    container_name: code-server1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
    #   - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
        cd /config/workspace
        sudo -u abc git clone https://github.com/coolboy0961/learn-clean-architecture.git
        cd learn-clean-architecture/api/laravel10.x/
        sudo -u abc touch database.sqlite
        export COMPOSER_ALLOW_SUPERUSER=1
        export HOME=/config
        sudo -u abc composer install
        tail -f /dev/null
  code-server2:
    image: localhost/code-server-php8:latest
    container_name: code-server2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
    #   - ./config:/config
    ports:
      - 8444:8443
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
        cd /config/workspace
        sudo -u abc git clone https://github.com/coolboy0961/learn-clean-architecture.git
        cd learn-clean-architecture/api/laravel10.x/
        sudo -u abc touch database.sqlite
        export COMPOSER_ALLOW_SUPERUSER=1
        export HOME=/config
        sudo -u abc composer install
        tail -f /dev/null
  code-server3:
    image: localhost/code-server-php8:latest
    container_name: code-server3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
    #   - ./config:/config
    ports:
      - 8445:8443
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
        cd /config/workspace
        sudo -u abc git clone https://github.com/coolboy0961/learn-clean-architecture.git
        cd learn-clean-architecture/api/laravel10.x/
        sudo -u abc touch database.sqlite
        export COMPOSER_ALLOW_SUPERUSER=1
        export HOME=/config
        sudo -u abc composer install
        tail -f /dev/null