FROM lscr.io/linuxserver/code-server:latest
LABEL description="php-8.xの実行環境を構築した code-server container image"
LABEL maintainer="Jiadong Chen <jiadchen@redhat.com>"
SHELL ["/bin/bash", "-c"]
RUN apt update && \
    apt install -y apt-transport-https lsb-release ca-certificates software-properties-common default-jre && \
    add-apt-repository -y ppa:ondrej/php && \
    apt update && \
    apt install -y php8.2-fpm && \
    apt install -y php8.2-dom php8.2-xml php8.2-curl php8.2-zip unzip p7zip-full php8.2-cli && \
    apt install -y php8.2-mbstring php8.2-tokenizer php8.2-xmlwriter php-sqlite3 php-xdebug && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv ./composer.phar $(dirname $(which php))/composer && chmod +x "$_" && \
    git config --global user.name "Jiadong Chen" && \
    git config --global user.email "jiadchen@redhat.com" && \
    # libcurl4-openssl-dev \
    # libjpeg-dev \
    # libonig-dev \
    # libtidy-dev \
    # bzip2 \
    # build-essential \
    # pkg-config \
    # libxml2-dev \
    # libssl-dev \
    # libsqlite3-dev \
    # libbz2-dev \
    # libpng-dev \
    # libxslt1-dev \
    # libreadline-dev \
    # libzip-dev && \
    # git clone https://github.com/anyenv/anyenv ~/.anyenv && \
    # echo 'export PATH="$HOME/.anyenv/bin:$PATH"' >> ~/.bashrc && \
    # echo 'eval "$(anyenv init -)"' >> ~/.bashrc && \
    # source ~/.bashrc && \
    # anyenv --version && \
    # anyenv install --force-init && \
    # anyenv install phpenv && \
    # source ~/.bashrc && \
    # echo 'eval "$(phpenv init -)"' >> ~/.bashrc && \
    # source ~/.bashrc && \
    # phpenv install 8.2.3 && \
    # phpenv global 8.2.3 && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension dracula-theme.theme-dracula && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension oderwat.indent-rainbow && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension esbenp.prettier-vscode && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension PKief.material-icon-theme && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension mhutchie.git-graph && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension zobo.php-intellisense && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension mohamedbenhida.laravel-intellisense && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension recca0120.vscode-phpunit && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension felixfbecker.php-debug