FROM lscr.io/linuxserver/code-server:latest
LABEL description="python-3.10の実行環境を構築した code-server container image"
LABEL maintainer="Jiadong Chen <jiadchen@redhat.com>"
SHELL ["/bin/bash", "-c"]
RUN apt update && \
    apt install -y \
    build-essential \
    curl \
    libbz2-dev \
    libffi-dev \
    liblzma-dev \
    libncursesw5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libxml2-dev \
    libxmlsec1-dev \
    llvm \
    make \
    tk-dev \
    wget \
    xz-utils \
    zlib1g-dev \
    default-jre && \
    git clone https://github.com/anyenv/anyenv ~/.anyenv && \
    echo 'export PATH="$HOME/.anyenv/bin:$PATH"' >> ~/.bashrc && \
    echo 'eval "$(anyenv init -)"' >> ~/.bashrc && \
    source ~/.bashrc && \
    anyenv --version && \
    anyenv install --force-init && \
    anyenv install pyenv && \
    source ~/.bashrc && \
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc && \
    pyenv install 3.10.7 && \
    pyenv global 3.10.7 && \
    pip install pipenv && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension donjayamanne.python-extension-pack && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension dracula-theme.theme-dracula && \
    /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension littlefoxteam.vscode-python-test-adapter